// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Script struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	Code           string  `json:"code"`
	Enabled        int64   `json:"enabled"`
	ScheduleKind   string  `json:"schedule_kind"`
	ScheduleConfig string  `json:"schedule_config"`
	UserState      string  `json:"user_state"`
	LastRunAt      *string `json:"last_run_at"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

type ScriptLog struct {
	ID          int64  `json:"id"`
	ScriptRunID int64  `json:"script_run_id"`
	Level       string `json:"level"`
	Message     string `json:"message"`
	LoggedAt    string `json:"logged_at"`
}

type ScriptRun struct {
	ID             int64   `json:"id"`
	ScriptID       int64   `json:"script_id"`
	StartedAt      string  `json:"started_at"`
	FinishedAt     *string `json:"finished_at"`
	Status         string  `json:"status"`
	ErrorMessage   *string `json:"error_message"`
	SpawnedTaskIds string  `json:"spawned_task_ids"`
	Trigger        string  `json:"trigger"`
}

type Tag struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type Task struct {
	ID                int64    `json:"id"`
	Title             string   `json:"title"`
	Notes             string   `json:"notes"`
	State             string   `json:"state"`
	DueDate           *string  `json:"due_date"`
	Priority          float64  `json:"priority"`
	StagedOrder       *float64 `json:"staged_order"`
	SpawnedByScriptID *int64   `json:"spawned_by_script_id"`
	CreatedAt         string   `json:"created_at"`
	CompletedAt       *string  `json:"completed_at"`
	CancelledAt       *string  `json:"cancelled_at"`
	UpdatedAt         string   `json:"updated_at"`
}

type TaskTag struct {
	TaskID int64 `json:"task_id"`
	TagID  int64 `json:"tag_id"`
}
