// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	SelectRunsHealth(ctx context.Context) (int64, error)
	SelectScriptsHealth(ctx context.Context) (int64, error)
	SelectTagsHealth(ctx context.Context) (int64, error)
	SelectTasksHealth(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
