// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"
)

const selectRunsHealth = `-- name: SelectRunsHealth :one
SELECT COUNT(*) FROM script_runs
`

func (q *Queries) SelectRunsHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectRunsHealth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
