// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scripts.sql

package sqlcgen

import (
	"context"
)

const selectScriptsHealth = `-- name: SelectScriptsHealth :one
SELECT COUNT(*) FROM scripts
`

func (q *Queries) SelectScriptsHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectScriptsHealth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
