// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"
)

const countTagsByHue = `-- name: CountTagsByHue :many
SELECT color_hue, COUNT(*) AS count
FROM tags
GROUP BY color_hue
`

type CountTagsByHueRow struct {
	ColorHue int64 `json:"color_hue"`
	Count    int64 `json:"count"`
}

func (q *Queries) CountTagsByHue(ctx context.Context) ([]CountTagsByHueRow, error) {
	rows, err := q.db.QueryContext(ctx, countTagsByHue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTagsByHueRow
	for rows.Next() {
		var i CountTagsByHueRow
		if err := rows.Scan(&i.ColorHue, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color_hue) VALUES (?, ?) RETURNING id, name, created_at, color_hue
`

type CreateTagParams struct {
	Name     string `json:"name"`
	ColorHue int64  `json:"color_hue"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.ColorHue)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ColorHue,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, created_at, color_hue FROM tags WHERE id = ?
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ColorHue,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at, color_hue FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ColorHue,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at, color_hue FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ColorHue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCounts = `-- name: ListTagsWithCounts :many
SELECT t.id, t.name, t.color_hue, t.created_at, COALESCE(c.cnt, 0) AS count
FROM tags t
LEFT JOIN (
  SELECT tag_id, COUNT(DISTINCT task_id) AS cnt
  FROM task_tags
  GROUP BY tag_id
) c ON c.tag_id = t.id
ORDER BY t.name ASC
`

type ListTagsWithCountsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ColorHue  int64  `json:"color_hue"`
	CreatedAt string `json:"created_at"`
	Count     int64  `json:"count"`
}

func (q *Queries) ListTagsWithCounts(ctx context.Context) ([]ListTagsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithCountsRow
	for rows.Next() {
		var i ListTagsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorHue,
			&i.CreatedAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTag = `-- name: RenameTag :one
UPDATE tags SET name = ? WHERE id = ? RETURNING id, name, created_at, color_hue
`

type RenameTagParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, renameTag, arg.Name, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ColorHue,
	)
	return i, err
}
