// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"
)

const selectTagsHealth = `-- name: SelectTagsHealth :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) SelectTagsHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectTagsHealth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
