// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
)

const selectTasksHealth = `-- name: SelectTasksHealth :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) SelectTasksHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectTasksHealth)
	var count int64
	err := row.Scan(&count)
	return count, err
}
